/* Traductions arabes, partie 3. */
export const AR3: Record<string, string> = {
  "Raisonnement": "الاستدلال",
  "Rechercher dans tes discussions": "ابحث في محادثاتك",
  "Rechercher…": "بحث…",
  "Recommencer ce cas": "إعادة هذه الحالة",
  "Reçu choisi : {a}": "الإيصال المختار: {a}",
  "Référence :": "المرجع:",
  "Regénérer": "إعادة الإنشاء",
  "Regénérer la réponse": "إعادة إنشاء الإجابة",
  "Réglages": "الإعدادات",
  "Réinitialiser": "إعادة الضبط",
  "Rejoindre": "انضمام",
  "Rejoins une session": "انضم إلى جلسة",
  "Renommer « {a} »": "إعادة تسمية «{a}»",
  "Répéter ce morceau": "تكرار هذه المقطوعة",
  "Répéter la playlist": "تكرار القائمة",
  "Réponse": "الجواب",
  "Réponse attendue": "الجواب المنتظر",
  "Reprendre": "استئناف",
  "restant sur {c}": "متبقٍ من {c}",
  "restante": "متبقية",
  "restante sur {c}": "متبقية من {c}",
  "restantes": "متبقية",
  "restantes sur {c}": "متبقية من {c}",
  "restants sur {c}": "متبقية من {c}",
  "Résultat": "النتيجة",
  "Résultat · {a}": "النتيجة · {a}",
  "Retirer l'image {a}": "إزالة الصورة {a}",
  "Retour à la révision à deux": "العودة إلى المراجعة مع صديق",
  "Retour aux offres": "العودة إلى العروض",
  "Réviser": "المراجعة",
  "Réviser à deux": "المراجعة مع صديق",
  "Réviser à deux est réservé au plan Premium.": "المراجعة مع صديق مخصّصة لاشتراك Premium.",
  "Réviser quand même": "راجع على أي حال",
  "Révision à deux": "المراجعة مع صديق",
  "Revoir la correction": "مراجعة التصحيح",
  "Revoir les cartes difficiles": "مراجعة البطاقات الصعبة",
  "Rien encore cette semaine.": "لا شيء بعد هذا الأسبوع.",
  "Rien n'a été débité. Tu peux réessayer quand tu veux.": "لم يُخصم أي مبلغ. يمكنك المحاولة متى شئت.",
  "Ruisseau {n}": "جدول ماء {n}",
  "Sans cours": "بلا درس",
  "Sans réponse": "بلا إجابة",
  "Sans réponse · 0 point": "بلا إجابة · 0 نقطة",
  "Se déconnecter": "تسجيل الخروج",
  "Sénégal": "السنغال",
  "Série de QCM": "سلسلة QCM",
  "Séries de QCM": "سلاسل QCM",
  "Session de révision": "جلسة مراجعة",
  "Session introuvable": "الجلسة غير موجودة",
  "Session terminée !": "انتهت الجلسة!",
  "Seules les images sont acceptées pour l'instant.": "الصور وحدها مقبولة حاليًا.",
  "Si tu as bien payé, ton plan s'active tout seul dès que l'opérateur confirme, en général en quelques minutes. Tu peux fermer cette page.": "إذا دفعت فعلًا، يُفعَّل اشتراكك تلقائيًا بمجرد تأكيد المشغّل، عادةً خلال دقائق. يمكنك إغلاق هذه الصفحة.",
  "Signaler une erreur": "الإبلاغ عن خطأ",
  "Signaler une erreur dans ce cas": "الإبلاغ عن خطأ في هذه الحالة",
  "Signaler une erreur dans cette fiche": "الإبلاغ عن خطأ في هذا الملخّص",
  "Signaler une erreur dans cette question": "الإبلاغ عن خطأ في هذا السؤال",
  "Sommaire": "الفهرس",
  "Sons à mélanger · plusieurs à la fois, par-dessus la musique si tu veux": "أصوات للمزج · عدة أصوات معًا، فوق الموسيقى إن شئت",
  "Standard": "Standard",
  "Suivante →": "التالية ←",
  "Supprimer": "حذف",
  "Supprimer « {a} »": "حذف «{a}»",
  "Supprimer {a}": "حذف {a}",
  "Supprimer ce cours ?": "حذف هذا الدرس؟",
  "Supprimer cette discussion ?": "حذف هذه المحادثة؟",
  "Supprimer cette série": "حذف هذه السلسلة",
  "Supprimer cette série ?": "حذف هذه السلسلة؟",
  "Supprimer cette session": "حذف هذه الجلسة",
  "Supprimer la discussion": "حذف المحادثة",
  "Supprimer la série": "حذف السلسلة",
  "Supprimer le cours": "حذف الدرس",
  "sur {a}": "من {a}",
  "Ta filière": "تخصصك",
  "Ta génération du jour est utilisée": "استُهلكت عمليات الإنشاء المسموحة اليوم",
  "Ta progression est gardée sur cet appareil pour le moment.": "تقدّمك محفوظ على هذا الجهاز حاليًا.",
  "Ta question": "سؤالك",
  "Ta semaine": "أسبوعك",
  "terminé": "منتهية",
  "Terminer": "إنهاء",
  "Terminer l'enregistrement": "إنهاء التسجيل",
  "Terminer maintenant": "إنهاء الآن",
  "Tes discussions": "محادثاتك",
  "Tes discussions apparaîtront ici.": "ستظهر محادثاتك هنا.",
  "Tes QCM du jour sont faits": "أنهيت أسئلة QCM المسموحة اليوم",
  "Tes séries précédentes": "سلاسلك السابقة",
  "Tes sessions": "جلساتك",
  "Toi": "أنت",
  "Ton abonnement": "اشتراكك",
  "Ton année": "سنتك الدراسية",
  "Ton cours est prêt.": "درسك جاهز.",
  "Ton message": "رسالتك",
  "Ton navigateur ne permet pas l'enregistrement vocal.": "متصفحك لا يدعم التسجيل الصوتي.",
  "Ton numéro {a}": "رقمك {a}",
  "ton partenaire": "صديقك",
  "Ton partenaire": "صديقك",
  "Ton partenaire n'a pas besoin d'abonnement : l'invitation est gratuite.": "صديقك لا يحتاج إلى اشتراك: الدعوة مجانية.",
  "Ton pays": "بلدك",
  "Ton plan": "اشتراكك",
  "Ton plan {a} permet {b} par jour.": "اشتراك {a} يتيح لك {b} يوميًا.",
  "Ton plan a une limite de documents. Supprime un ancien cours pour en ajouter un nouveau, ou passe au plan {p} pour en avoir plus.": "لاشتراكك حدّ للمستندات. احذف درسًا قديمًا لإضافة درس جديد، أو انتقل إلى اشتراك {p} للحصول على المزيد.",
  "Ton plan actuel": "اشتراكك الحالي",
  "Ton plan est activé automatiquement dès que le paiement est confirmé.": "يُفعَّل اشتراكك تلقائيًا فور تأكيد الدفع.",
  "Ton plan est activé sous 24 heures après vérification.": "يُفعَّل اشتراكك خلال 24 ساعة بعد التحقق.",
  "Ton plan permet {n} document. Supprime un ancien cours pour en ajouter un nouveau, ou passe au plan {p} pour en avoir plus.": "اشتراكك يتيح {n} مستندًا. احذف درسًا قديمًا لإضافة درس جديد، أو انتقل إلى اشتراك {p} للحصول على المزيد.",
  "Ton plan permet {n} documents. Supprime un ancien cours pour en ajouter un nouveau, ou passe au plan {p} pour en avoir plus.": "اشتراكك يتيح {n} مستندات. احذف درسًا قديمًا لإضافة درس جديد، أو انتقل إلى اشتراك {p} للحصول على المزيد.",
  "Ton prénom": "اسمك الأول",
  "Ton profil": "ملفك الشخصي",
  "Ton signalement sera relu et le contenu corrigé si besoin. En attendant, fie-toi à ton cours et à ton enseignant.": "سنراجع بلاغك ونصحّح المحتوى عند الحاجة. في الأثناء، اعتمد على درسك وعلى أستاذك.",
  "Ton université": "جامعتك",
  "Ton usage aujourd'hui": "استخدامك اليوم",
  "Touche la carte pour voir la réponse": "المس البطاقة لرؤية الجواب",
  "Tous les outils": "كل الأدوات",
  "Tout arrêter": "إيقاف كل شيء",
  "Tout est à jour": "كل شيء محدّث",
  "Transcription en cours…": "جارٍ التفريغ الصوتي…",
  "Travaille par blocs de concentration, puis fais une pause. Chaque bloc terminé est enregistré.": "اعمل على فترات تركيز، ثم خذ استراحة. تُسجَّل كل فترة منتهية.",
  "Tu as atteint la limite de dictées du jour.": "بلغت حدّ الإملاء الصوتي لهذا اليوم.",
  "Tu as atteint la limite de pages lues aujourd'hui ({a}). Réessaie demain, ou passe à un plan supérieur pour en lire davantage.": "بلغت حدّ الصفحات المقروءة اليوم ({a}). حاول غدًا، أو انتقل إلى اشتراك أعلى لقراءة المزيد.",
  "Tu as atteint la limite de pages lues aujourd'hui. Réessaie demain, ou passe à un plan supérieur pour en lire davantage.": "بلغت حدّ الصفحات المقروءة اليوم. حاول غدًا، أو انتقل إلى اشتراك أعلى لقراءة المزيد.",
  "Tu as déjà 3 demandes en attente de vérification. Attends leur validation ou écris-nous sur WhatsApp.": "لديك بالفعل 3 طلبات في انتظار التحقق. انتظر تأكيدها أو راسلنا على واتساب.",
  "Tu as déjà plusieurs paiements en attente. Termine-les ou attends quelques minutes.": "لديك بالفعل عدة مدفوعات معلّقة. أنهِها أو انتظر بضع دقائق.",
  "Tu as déjà revu ces cartes aujourd'hui. La répétition espacée te les représentera au bon moment.": "راجعت هذه البطاقات اليوم بالفعل. سيعرضها عليك التكرار المتباعد في الوقت المناسب.",
  "Tu as invité": "دعوتَ",
  "Tu as posé toutes tes questions du jour": "طرحت كل أسئلتك المسموحة اليوم",
  "Tu as reçu une invitation": "وصلتك دعوة",
  "Tu as rejoint": "انضممتَ",
  "Tu as utilisé toutes tes questions du jour.": "استعملت كل أسئلتك المسموحة اليوم.",
  "Tu choisis ton moyen de paiement sur la page suivante : mobile money (Wave, Orange Money, Free Money…) ou carte bancaire.": "تختار وسيلة الدفع في الصفحة التالية: الدفع عبر الهاتف (Wave، Orange Money، Free Money…) أو بطاقة بنكية.",
  "Tu en étais à": "وصلتَ إلى",
  "Tu invites un ami, qui participe gratuitement, et vous comparez vos réponses.": "تدعو صديقًا يشارك مجانًا، وتقارنان إجاباتكما.",
  "Tu paies dans l'application de ton opérateur. Ton plan est activé automatiquement, sans reçu à envoyer.": "تدفع في تطبيق مشغّلك. يُفعَّل اشتراكك تلقائيًا دون إيصال لإرساله.",
  "Tu peux en profiter tout de suite, sur le site et dans l'application.": "يمكنك الاستفادة منه فورًا، على الموقع وفي التطبيق.",
  "Tu peux joindre {a} images au maximum.": "يمكنك إرفاق {a} صور كحدّ أقصى.",
  "Un cas concret pour t'entraîner comme à l'examen.": "حالة واقعية لتتدرب كما في الامتحان.",
  "Un ou plusieurs cas en 4 étapes (motif, interrogatoire, examen, examens complémentaires). Tu réfléchis avant de voir la suite, puis le diagnostic.": "حالة أو أكثر في 4 مراحل (سبب الاستشارة، الاستجواب، الفحص، الفحوص التكميلية). تفكّر قبل رؤية التالي، ثم التشخيص.",
  "Une erreur est survenue.": "حدث خطأ.",
  "Une ou plusieurs propositions sont exactes.": "اقتراح واحد أو أكثر صحيح.",
  "Une série de QCM, deux personnes. Chacun répond à son rythme, vous voyez où en est l'autre, puis vous comparez vos réponses question par question.": "سلسلة QCM واحدة لشخصين. يجيب كل منكما بوتيرته، وترى أين وصل الآخر، ثم تقارنان إجاباتكما سؤالًا بسؤال.",
  "Université": "الجامعة",
  "Vagues": "أمواج",
  "Vagues et brise": "أمواج ونسيم",
  "Validation…": "جارٍ التأكيد…",
  "Valide toutes les questions pour voir le résultat de la session.": "أجب عن كل الأسئلة لترى نتيجة الجلسة.",
  "Valider": "تأكيد",
  "Vent": "رياح",
  "Vérification du paiement…": "جارٍ التحقق من الدفع…",
  "Visa, Mastercard": "Visa، Mastercard",
  "Voir la fiche": "عرض الملخّص",
  "Voir la question": "عرض السؤال",
  "Voir la réponse": "عرض الجواب",
  "Voir le diagnostic": "عرض التشخيص",
  "Voir le plan {a}": "عرض اشتراك {a}",
  "Voir le plan Premium": "عرض اشتراك Premium",
  "Voir le résultat": "عرض النتيجة",
  "Voir le résultat de la série": "عرض نتيجة السلسلة",
  "Voir les offres": "عرض العروض",
  "Voir les plans": "عرض الاشتراكات",
  "Voir les plans →": "عرض الاشتراكات ←",
  "Voir mon résultat": "عرض نتيجتي",
  "Volume : {a}": "مستوى الصوت: {a}",
  "Volume de la musique": "مستوى صوت الموسيقى",
  "Volume général": "مستوى الصوت العام",
  "Volume musique": "صوت الموسيقى",
  "Wave": "Wave",
  "{a} question pas encore validée : elle comptera 0 point si tu termines maintenant.": "{a} سؤال لم تُجب عنه بعد: سيُحتسب بصفر نقطة إن أنهيت الآن.",
  "{a} questions pas encore validées : elles compteront 0 point si tu termines maintenant.": "{a} أسئلة لم تُجب عنها بعد: ستُحتسب بصفر نقطة إن أنهيت الآن.",
  "40 questions par jour à Dr. Ahmed": "40 سؤالًا يوميًا للدكتور أحمد",
  "50 documents actifs": "50 مستندًا نشطًا",
  "5 fiches, flashcards ou cas cliniques par jour": "5 ملخّصات أو بطاقات مراجعة أو حالات سريرية يوميًا",
  "50 questions de QCM par jour": "50 سؤال QCM يوميًا",
  "Export des fiches en PDF": "تصدير الملخّصات بصيغة PDF",
  "Historique de 30 jours": "سجل لمدة 30 يومًا",
  "Révision à deux : QCM partagés avec un ami, invité gratuit": "المراجعة مع صديق: سلاسل QCM مشتركة، والمدعو مجانًا",
  "100 questions par jour à Dr. Ahmed": "100 سؤال يوميًا للدكتور أحمد",
  "Documents illimités": "مستندات غير محدودة",
  "20 fiches, flashcards ou cas cliniques par jour": "20 ملخّصًا أو بطاقة مراجعة أو حالة سريرية يوميًا",
  "150 questions de QCM par jour": "150 سؤال QCM يوميًا",
  "Historique illimité": "سجل غير محدود",
  "La révision à deux est réservée au plan Premium.": "المراجعة مع صديق مخصّصة لاشتراك Premium.",
  "Tu as déjà créé 10 sessions aujourd'hui. Reprends une session en cours ou réessaie demain.": "أنشأت اليوم 10 جلسات بالفعل. تابع جلسة جارية أو حاول غدًا.",
  "Ce code ne correspond à aucune session. Vérifie-le avec ton partenaire.": "هذا الرمز لا يطابق أي جلسة. تحقّق منه مع صديقك.",
  "Cette session est terminée (elle dure 48 heures).": "انتهت هذه الجلسة (مدتها 48 ساعة).",
  "Cette session a déjà deux participants.": "لهذه الجلسة مشاركان بالفعل.",
  "Tu ne fais pas partie de cette session.": "أنت لست ضمن هذه الجلسة.",
  "La discussion de cette session est pleine.": "محادثة هذه الجلسة ممتلئة.",
  "Connecte-toi pour continuer.": "سجّل الدخول للمتابعة.",
  "Le service est indisponible pour le moment. Réessaie dans un instant.": "الخدمة غير متاحة حاليًا. حاول بعد قليل.",
  "Le service n'est pas configuré.": "الخدمة غير مُعدّة.",
  "Motif de consultation": "سبب الاستشارة",
  "Interrogatoire": "الاستجواب",
  "Examen clinique": "الفحص السريري",
  "Examens complémentaires": "الفحوص التكميلية",
  "Étape 1 sur 2 : écriture des cas…": "المرحلة 1 من 2: كتابة الحالات…",
  "Étape 2 sur 2 : vérification médicale…": "المرحلة 2 من 2: التحقق الطبي…",
  "Le service est indisponible.": "الخدمة غير متاحة.",
  "Tu as atteint ta limite du jour. Reviens demain ou passe à un plan supérieur.": "بلغت حدّك اليومي. عد غدًا أو انتقل إلى اشتراك أعلى.",
  "Impossible d'enregistrer. Réessaie.": "تعذّر الحفظ. حاول مجددًا.",
  "{a} ne savait pas la carte précédente.": "{a} لم يكن يعرف البطاقة السابقة.",
  "{a} peut t'expliquer": "{a} يستطيع أن يشرح لك",
  "{a} savait la carte précédente.": "{a} كان يعرف البطاقة السابقة.",
  "À revoir ensemble : aucun de vous deux ne les savait": "للمراجعة معًا: لم يكن أيٌّ منكما يعرفها",
  "cartes sues": "بطاقات معروفة",
  "Cas clinique": "حالة سريرية",
  "Cas clinique à deux": "حالة سريرية مع صديق",
  "Ce contenu ne peut pas être partagé.": "لا يمكن مشاركة هذا المحتوى.",
  "Clique sur « Réviser à deux » (ou « Salle à deux »).": "اضغط على «المراجعة مع صديق» (أو «غرفة مع صديق»).",
  "Comparer vos raisonnements": "مقارنة استدلالَيكما",
  "Cours partagé": "درس مشترك",
  "Demander à Dr. Ahmed": "اسأل الدكتور أحمد",
  "Dès que {a} a terminé le cas, Dr. Ahmed pourra comparer vos deux raisonnements.": "بمجرد أن ينهي {a} الحالة، سيقارن الدكتور أحمد بين استدلالَيكما.",
  "Diagnostic final": "التشخيص النهائي",
  "Discussion avec Dr. Ahmed": "محادثة مع الدكتور أحمد",
  "Dr. Ahmed répond d'après ce cours, puis va plus loin si besoin. Seul ce cours est partagé dans la salle, pas le reste de tes documents.": "يجيب الدكتور أحمد انطلاقًا من هذا الدرس، ثم يتوسّع عند الحاجة. هذا الدرس وحده مشترك في الغرفة، وليس باقي مستنداتك.",
  "Écris ton raisonnement…": "اكتب استدلالك…",
  "Écris un petit mot à ton partenaire : il apparaîtra ici.": "اكتب كلمة صغيرة إلى صديقك: ستظهر هنا.",
  "Envoyer à {a}": "إرسال إلى {a}",
  "Essaie de répondre de tête, puis touche la carte": "حاول أن تجيب من الذاكرة، ثم المس البطاقة",
  "Flashcards à deux": "بطاقات مراجعة مع صديق",
  "Il lui reste des cartes : son score peut encore changer.": "بقيت له بطاقات: قد تتغير نتيجته.",
  "Je ne savais pas": "لم أكن أعرف",
  "Je savais": "كنت أعرف",
  "Le quota du jour de l'abonné Premium est atteint. Réessayez demain.": "بلغ المشترك Premium حدّه اليومي. حاولا غدًا.",
  "Ouvre un cours et choisis QCM, flashcards, cas cliniques ou questions.": "افتح درسًا واختر QCM أو بطاقات المراجعة أو الحالات السريرية أو الأسئلة.",
  "Posez vos questions à Dr. Ahmed : vous voyez tous les deux ses réponses. Vous pouvez aussi vous écrire entre vous.": "اطرحا أسئلتكما على الدكتور أحمد: يرى كلاكما إجاباته. ويمكنكما أيضًا المراسلة بينكما.",
  "QCM à deux": "QCM مع صديق",
  "Quel est ton diagnostic final, et pourquoi ?": "ما هو تشخيصك النهائي، ولماذا؟",
  "Réponds honnêtement : tu vois ensuite ce qu'en dit ton partenaire": "أجب بصدق: سترى بعدها ما يقوله صديقك",
  "Révisez à deux : des QCM, des flashcards, un cas clinique ou une salle avec Dr. Ahmed. Chacun avance à son rythme, vous voyez où en est l'autre, puis vous comparez vos réponses.": "راجعا معًا: أسئلة QCM أو بطاقات مراجعة أو حالة سريرية أو غرفة مع الدكتور أحمد. يتقدّم كل منكما بوتيرته، وترى أين وصل الآخر، ثم تقارنان إجاباتكما.",
  "Salle avec Dr. Ahmed": "غرفة مع الدكتور أحمد",
  "Session à deux": "جلسة مع صديق",
  "Ta question ou ton message": "سؤالك أو رسالتك",
  "Ton raisonnement": "استدلالك",
  "Tu peux expliquer à {a}": "يمكنك أن تشرح لـ {a}",
  "Tu vois la réponse de {a} dès que tu as validé la tienne.": "سترى إجابة {a} بمجرد أن تؤكد إجابتك.",
  "Valider ma réponse": "تأكيد إجابتي",
  "Vous avez tous les deux terminé. Dr. Ahmed compare vos raisonnements avec celui du cas, et dit ce que chacun peut apprendre de l'autre.": "أنهيتما كلاكما. يقارن الدكتور أحمد استدلالَيكما باستدلال الحالة، ويبيّن ما يستطيع كل منكما أن يتعلمه من الآخر.",
  "Vous devez tous les deux avoir terminé le cas.": "يجب أن ينهي كلاكما الحالة.",
  "Mauritanie": "موريتانيا",
  "Maroc": "المغرب",
}
