/* Traductions arabes, partie 1 (clé = texte français du code). */
export const AR1: Record<string, string> = {
  "« {a} » sera supprimé définitivement, avec sa fiche, ses flashcards et ses cas cliniques. Tu pourras ensuite ajouter un autre document.":
    "سيُحذف «{a}» نهائيًا مع ملخّصه وبطاقات المراجعة والحالات السريرية الخاصة به. يمكنك بعد ذلك إضافة مستند آخر.",
  "« {a} » sera supprimée définitivement, avec tous ses messages.": "ستُحذف «{a}» نهائيًا مع جميع رسائلها.",
  "(facultatif)": "(اختياري)",
  "(recommandé)": "(موصى به)",
  "(sinon il continue jusqu'à ce que tu l'arrêtes)": "(وإلا فسيستمر حتى توقفه)",
  "{a} · {b} pts": "{a} · {b} نقطة",
  "{a} cartes revues, tout est acquis": "تمت مراجعة {a} بطاقة، وكل شيء متقن",
  "{a} carte à revoir sur {b}": "{a} بطاقة للمراجعة من أصل {b}",
  "{a} cartes à revoir sur {b}": "{a} بطاقات للمراجعة من أصل {b}",
  "{a} de Pomodoro": "{a} من البومودورو",
  "{a} min": "{a} د",
  "{a} morceaux · {b} min · {c}": "{a} مقطوعات · {b} د · {c}",
  "{a} MRU par mois": "⁦{a} MRU⁩ شهريًا",
  "{a} MRU par mois. ": "⁦{a} MRU⁩ شهريًا. ",
  "{a} par jour": "{a} يوميًا",
  "{a} sur {b}": "{a} من {b}",
  "{a} travaillées ces 7 derniers jours": "{a} من العمل خلال آخر 7 أيام",
  "{a} page": "{a} صفحة",
  "{a} pages": "{a} صفحات",
  "{a} sessions ce mois-ci": "{a} جلسات هذا الشهر",
  "{a} session ce mois-ci": "{a} جلسة هذا الشهر",
  "+{a} autre": "+{a} آخر",
  "+{a} autres": "+{a} أخرى",
  "{a} bloc terminé": "{a} جولة منتهية",
  "{a} blocs terminés": "{a} جولات منتهية",
  "· {a} son de nature": "· {a} صوت طبيعي",
  "· {a} sons de nature": "· {a} أصوات طبيعية",
  "{a} carte maîtrisée sur {b}": "{a} بطاقة متقنة من أصل {b}",
  "{a} cartes maîtrisées sur {b}": "{a} بطاقات متقنة من أصل {b}",
  "{a} maîtrisée sur {b}": "{a} متقنة من أصل {b}",
  "{a} maîtrisées sur {b}": "{a} متقنة من أصل {b}",
  "{a}/{b} répondues · {c} pts": "{a}/{b} إجابة · {c} نقطة",
  "{n} fiche, série de flashcards ou cas clinique": "{n} ملخّص أو سلسلة بطاقات مراجعة أو حالة سريرية",
  "{n} fiches, séries de flashcards ou cas cliniques": "{n} ملخّصات أو سلاسل بطاقات مراجعة أو حالات سريرية",
  "{n} question à Dr. Ahmed": "{n} سؤال للدكتور أحمد",
  "{n} questions à Dr. Ahmed": "{n} أسئلة للدكتور أحمد",
  "{n} série de QCM": "{n} سلسلة QCM",
  "{n} séries de QCM": "{n} سلاسل QCM",
  "{n} session": "{n} جلسة",
  "{n} sessions": "{n} جلسات",
  "← Changer d'offre": "→ تغيير العرض",
  "← Mes séries": "→ سلاسلي",
  "← Précédente": "→ السابقة",
  "← Révision à deux": "→ المراجعة مع صديق",
  "⏱ {a} travaillées en Pomodoro": "⏱ {a} من العمل بنظام بومودورو",
  "1 matière": "مادة واحدة",
  "3 matières": "3 مواد",
  "25 % d'économie sur l'année": "توفير 25 % على السنة",
  "30 derniers jours": "آخر 30 يومًا",
  "5 questions pour vérifier ce que tu as retenu, avec la correction.": "5 أسئلة للتأكد مما حفظته، مع التصحيح.",
  "7 derniers jours": "آخر 7 أيام",
  "À revoir": "أراجعها",
  "Abonnement": "الاشتراك",
  "Accès complet": "وصول كامل",
  "Accords planants, sans rythme": "ألحان هادئة بلا إيقاع",
  "Accueil": "الرئيسية",
  "Actif jusqu'au {a}.": "ساري حتى {a}.",
  "Ajout…": "جارٍ الإضافة…",
  "Ajoute ton premier cours pour commencer à réviser.": "أضف أول درس لك لتبدأ المراجعة.",
  "Ajoute un document plus complet, ou des photos plus nettes de tes pages.": "أضف مستندًا أكمل، أو صورًا أوضح لصفحاتك.",
  "Ajoute un PDF (même scanné), des photos de tes pages de cours ou un fichier .txt. Une fois lu, tu choisis quoi en faire : poser des questions, une fiche, des QCM, des flashcards ou un cas clinique.":
    "أضف ملف PDF (حتى لو كان ممسوحًا ضوئيًا) أو صور صفحات درسك أو ملف .txt. بعد قراءته تختار ما تفعله به: أسئلة، ملخّص، أسئلة QCM، بطاقات مراجعة أو حالة سريرية.",
  "Ajoute-la ici": "أضفها هنا",
  "Ajouter un cours": "إضافة درس",
  "Ajouter un document": "إضافة مستند",
  "Ajouter une session": "إضافة جلسة",
  "Aléatoire": "عشوائي",
  "Ambiance sonore": "أجواء صوتية",
  "Ambiances prêtes · un clic": "أجواء جاهزة · بنقرة واحدة",
  "Année": "السنة",
  "Annuel": "سنوي",
  "Annuler": "إلغاء",
  "Appuie sur le micro pour terminer": "اضغط على الميكروفون للإنهاء",
  "arabe": "العربية",
  "Arrêter la musique": "إيقاف الموسيقى",
  "Arrêter la réponse": "إيقاف الإجابة",
  "au Maroc": "في المغرب",
  "au numéro": "على الرقم",
  "au Sénégal": "في السنغال",
  "Aucun cas clinique fiable n'a pu être construit à partir de ce cours. Il faut une pathologie ou une situation clinique traitée dans le cours.":
    "تعذّر بناء حالة سريرية موثوقة من هذا الدرس. يلزم أن يتناول الدرس مرضًا أو وضعًا سريريًا.",
  "Aucune discussion trouvée.": "لم يتم العثور على أي محادثة.",
  "Aucune série pour l'instant. Tes QCM seront enregistrés ici pour les réviser plus tard.": "لا توجد سلاسل بعد. ستُحفظ أسئلة QCM هنا لتراجعها لاحقًا.",
  "Aucune session ce jour-là.": "لا توجد جلسات في هذا اليوم.",
  "Aucune session pour l'instant. Elles apparaîtront ici pendant 48 heures.": "لا توجد جلسات بعد. ستظهر هنا لمدة 48 ساعة.",
  "Aucune session prévue. Planifie-en une pour garder le rythme.": "لا توجد جلسة مبرمجة. خطّط لواحدة لتحافظ على وتيرتك.",
  "Augmenter mes limites →": "رفع حدودي ←",
  "Aujourd'hui": "اليوم",
  "automatique, français ou arabe": "تلقائي، فرنسية أو عربية",
  "Avancement du morceau": "تقدّم المقطوعة",
  "Avec {a}": "مع {a}",
  "Averse et grondement grave": "زخّات مطر ورعد خافت",
  "Axone, accueil": "أكسون، الرئيسية",
  "Beats doux": "إيقاعات هادئة",
  "Besoin d'aide ? WhatsApp": "تحتاج مساعدة؟ واتساب",
  "Bien": "جيدة",
  "Bientôt": "قريبًا",
  "Bienvenue sur Axone.": "مرحبًا بك في أكسون.",
  "Bonjour {a}, qu'est-ce qu'on révise ?": "مرحبًا {a}، ماذا سنراجع اليوم؟",
  "Bonjour {a}, que veux-tu réviser ?": "مرحبًا {a}، ماذا تريد أن تراجع؟",
  "Bonjour {a}.": "مرحبًا {a}.",
  "Bord de mer": "شاطئ البحر",
  "Bruit blanc": "ضجيج أبيض",
  "Bruit brun": "ضجيج بنّي",
  "Bruit brun et nappes calmes": "ضجيج بنّي وألحان هادئة",
  "Bruit rose": "ضجيج وردي",
  "Bruits de fond": "ضجيج الخلفية",
  "Ça prend en général 20 à 30 secondes. Ne ferme pas la page.": "يستغرق ذلك عادةً من 20 إلى 30 ثانية. لا تغلق الصفحة.",
  "Ça prend en général 20 à 60 secondes. Ne ferme pas la page.": "يستغرق ذلك عادةً من 20 إلى 60 ثانية. لا تغلق الصفحة.",
  "Café": "مقهى",
  "Capture du reçu de paiement": "لقطة شاشة لإيصال الدفع",
  "Carte {a} sur {b}": "البطاقة {a} من {b}",
  "Carte bancaire": "بطاقة بنكية",
  "Cas {a}": "الحالة {a}",
  "Cas clinique · fictif, à visée pédagogique": "حالة سريرية · افتراضية لغرض تعليمي",
  "Cas cliniques": "حالات سريرية",
  "Ce document a {a} pages : la lecture d'un scan ou de photos est limitée à {b} pages à la fois. Découpe-le en plusieurs parties.":
    "يحتوي هذا المستند على {a} صفحة: قراءة المسح الضوئي أو الصور محدودة بـ {b} صفحة في المرة الواحدة. قسّمه إلى عدة أجزاء.",
  "Ce document est introuvable sur ton compte.": "هذا المستند غير موجود في حسابك.",
  "Ce document n'a pas assez de texte pour des QCM.": "لا يحتوي هذا المستند على نص كافٍ لأسئلة QCM.",
  "ce mois-ci": "هذا الشهر",
  "Ce PDF est un scan, lecture des pages…": "هذا الملف ممسوح ضوئيًا، جارٍ قراءة الصفحات…",
  "Ce que tu peux faire avec ce cours": "ما يمكنك فعله بهذا الدرس",
  "Cette discussion": "هذه المحادثة",
  "Cette image n'a pas pu être lue. Essaie un fichier JPG ou PNG.": "تعذّرت قراءة هذه الصورة. جرّب ملف JPG أو PNG.",
  "Cette session est terminée : tu peux revoir les réponses, plus en ajouter.": "انتهت هذه الجلسة: يمكنك مراجعة الإجابات دون إضافة غيرها.",
  "Chapitre": "الفصل",
  "Chapitre {a} sur {b}…": "الفصل {a} من {b}…",
  "Chaque ligne : tes points, puis ceux de {a}.": "كل سطر: نقاطك، ثم نقاط {a}.",
  "Chargement de la discussion…": "جارٍ تحميل المحادثة…",
  "Chargement de la musique…": "جارٍ تحميل الموسيقى…",
  "Chargement de la session…": "جارٍ تحميل الجلسة…",
  "Chargement de tes cartes…": "جارٍ تحميل بطاقاتك…",
  "Chargement de ton espace…": "جارٍ تحميل فضائك…",
  "Chargement des années…": "جارٍ تحميل السنوات…",
  "Chargement des moyens de paiement…": "جارٍ تحميل وسائل الدفع…",
  "Chargement des offres…": "جارٍ تحميل العروض…",
  "Chargement du document…": "جارٍ تحميل المستند…",
  "Chargement…": "جارٍ التحميل…",
  "Choisir {a}": "اختر {a}",
  "Choisir un cours": "اختر درسًا",
  "Choisir un PDF": "اختر ملف PDF",
  "Choisir une image": "اختر صورة",
  "Choisis ce que tu veux faire. Pour commencer, on te conseille la fiche, puis un QCM pour te tester.": "اختر ما تريد فعله. للبداية ننصحك بالملخّص، ثم أسئلة QCM لاختبار نفسك.",
  "Choisis un seul PDF ou fichier texte à la fois. Pour plusieurs pages, envoie des photos.": "اختر ملف PDF أو ملفًا نصيًا واحدًا فقط في كل مرة. لعدة صفحات، أرسل صورًا.",
  "Choisis une série, puis « Réviser à deux ».": "اختر سلسلة ثم «المراجعة مع صديق».",
  "Clavier : espace pour retourner, 1 à 4 pour noter, flèches pour parcourir.": "لوحة المفاتيح: المسافة للقلب، من 1 إلى 4 للتقييم، الأسهم للتنقل.",
  "Code": "الرمز",
  "Code de la session": "رمز الجلسة",
  "Coin du feu": "ركن المدفأة",
  "Colle le code à 6 caractères reçu de ton partenaire. C'est gratuit.": "الصق الرمز المكوّن من 6 أحرف الذي وصلك من صديقك. الأمر مجاني.",
  "Commencer à réviser": "ابدأ المراجعة",
  "Comment veux-tu payer ?": "كيف تريد أن تدفع؟",
  "Compris": "فهمت",
  "Compte Google": "حساب Google",
  "Concentration profonde": "تركيز عميق",
  "Conduite à tenir": "التدبير العلاجي",
  "Connecte-toi avec ce même compte Google dans l'application (Réglages, puis Compte) pour retrouver tes cours, ton plan et tes documents partout.":
    "سجّل الدخول بنفس حساب Google في التطبيق (الإعدادات ثم الحساب) لتجد دروسك واشتراكك ومستنداتك في كل مكان.",
  "Connexion": "تسجيل الدخول",
  "Connexion en cours…": "جارٍ تسجيل الدخول…",
  "Connexion…": "جارٍ الاتصال…",
  "Copié": "تم النسخ",
  "Copier": "نسخ",
  "Copier la réponse": "نسخ الإجابة",
  "Copier le lien": "نسخ الرابط",
  "Cours": "الدرس",
  "Cours utilisé pour répondre": "الدرس المستخدم في الإجابة",
  "Création de la session…": "جارٍ إنشاء الجلسة…",
  "Création…": "جارٍ الإنشاء…",
  "Crépitements": "طقطقة",
  "Dans ton cours": "في درسك",
  "de nature": "من الطبيعة",
  "Découpage en parties…": "جارٍ التقسيم إلى أجزاء…",
  "Décris l'erreur en une ou deux phrases. Une copie de ce contenu nous est envoyée.": "صِف الخطأ في جملة أو جملتين. تصلنا نسخة من هذا المحتوى.",
  "Déjà prêt": "جاهز مسبقًا",
  "Demain": "غدًا",
  "Demande envoyée.": "تم إرسال الطلب.",
  "Démarrer": "ابدأ",
  "Dépose ton premier cours.": "ارفع أول درس لك.",
  "Dernier cours ajouté.": "آخر درس أُضيف.",
  "Des cartes question / réponse pour mémoriser par cœur.": "بطاقات سؤال / جواب للحفظ عن ظهر قلب.",
  "Description de l'erreur": "وصف الخطأ",
  "Diagnostic": "التشخيص",
  "Diagnostics différentiels": "التشخيصات التفريقية",
  "Dicter avec le micro": "الإملاء بالميكروفون",
  "Difficile": "صعبة",
  "Dis-moi ton année et je m'adapte. En P1 et P2, je reviens sur les bases. En P3 et P4, je relie les mécanismes à la clinique. En P5 et en Résidanat, j'insiste sur les urgences, les complications et les pièges d'examen.":
    "أخبرني بسنتك وسأتكيّف معك. في P1 وP2 أعود إلى الأساسيات. في P3 وP4 أربط الآليات بالسريريات. في P5 والإقامة أركّز على الاستعجالات والمضاعفات وفخاخ الامتحان.",
  "Discussion": "المحادثة",
  "Discuter": "ناقش",
  "Documents": "المستندات",
  "Doux et équilibré": "هادئ ومتوازن",
  "Dr. Ahmed": "الدكتور أحمد",
  "Dr. Ahmed · ton prof virtuel": "الدكتور أحمد · أستاذك الافتراضي",
  "Dr. Ahmed construit tes cas…": "الدكتور أحمد يُعدّ حالاتك…",
  "Dr. Ahmed écrit": "الدكتور أحمد يكتب",
  "Dr. Ahmed écrit ta fiche…": "الدكتور أحمد يكتب ملخّصك…",
  "Dr. Ahmed est indisponible pour le moment. Réessaie dans un instant.": "الدكتور أحمد غير متاح حاليًا. حاول بعد قليل.",
  "Dr. Ahmed lit ton cours et en tire une fiche de révision : l'essentiel, le mécanisme, le diagnostic, le traitement, les questions d'examen probables et les pièges.":
    "يقرأ الدكتور أحمد درسك ويستخرج منه ملخّص مراجعة: الأساسيات، والآلية، والتشخيص، والعلاج، وأسئلة الامتحان المحتملة، والفخاخ.",
  "Dr. Ahmed part de « {a} » puis va plus loin si besoin.": "ينطلق الدكتور أحمد من «{a}» ثم يتوسّع عند الحاجة.",
  "Dr. Ahmed part de ton document, puis va plus loin si besoin.": "ينطلق الدكتور أحمد من مستندك، ثم يتوسّع عند الحاجة.",
  "Dr. Ahmed prépare tes cartes…": "الدكتور أحمد يجهّز بطاقاتك…",
  "Dr. Ahmed prépare tes QCM…": "الدكتور أحمد يجهّز أسئلة QCM…",
  "Dr. Ahmed réfléchit…": "الدكتور أحمد يفكّر…",
  "Dr. Ahmed répond à partir de ton cours, avec les pages à relire.": "يجيب الدكتور أحمد انطلاقًا من درسك، مع الصفحات التي يجب إعادة قراءتها.",
  "Dr. Ahmed t'aide à réviser et peut se tromper : vérifie les points importants avec ton cours.": "يساعدك الدكتور أحمد على المراجعة وقد يخطئ: تحقّق من النقاط المهمة مع درسك.",
  "Premium": "Premium",
  "Durée": "المدة",
  "Durée de focus": "مدة التركيز",
  "Durée de pause": "مدة الاستراحة",
  "Écrire sur WhatsApp": "راسلنا على واتساب",
  "Écris ta question, dépose une image (page de cours, schéma, ECG) ou dicte-la avec le micro.": "اكتب سؤالك، أو ارفع صورة (صفحة درس، رسم، تخطيط قلب) أو أمله بالميكروفون.",
  "Écris ta question, dépose une image ou parle…": "اكتب سؤالك، أو ارفع صورة أو تكلّم…",
  "Écris un petit mot à {a} : il apparaîtra ici.": "اكتب كلمة صغيرة إلى {a}: ستظهر هنا.",
  "Écris-nous sur WhatsApp : nous activons ton plan {a} avec toi.": "راسلنا على واتساب: نفعّل معك اشتراك {a}.",
  "Elle doit montrer le montant et le numéro.": "يجب أن تُظهر المبلغ والرقم.",
  "Elles reviennent demain. Avec Standard, tu en as 30 par jour.": "تعود غدًا. مع Standard لديك 30 يوميًا.",
  "En attente d'un partenaire": "في انتظار شريك",
  "En attente de ton partenaire": "في انتظار صديقك",
  "En cours": "قيد التنفيذ",
  "En cours · {a} validée sur {b}": "قيد التنفيذ · {a} مُجابة من {b}",
  "En cours · {a} validées sur {b}": "قيد التنفيذ · {a} مُجابة من {b}",
  "Enregistrement": "تسجيل",
  "Enregistrement…": "جارٍ التسجيل…",
  "Enregistrer": "حفظ",
  "Envoi…": "جارٍ الإرسال…",
  "Envoie exactement {a} MRU avec {b}": "أرسل بالضبط ⁦{a} MRU⁩ عبر {b}",
  "Envoie le lien à ton partenaire (WhatsApp, par exemple).": "أرسل الرابط إلى صديقك (عبر واتساب مثلًا).",
  "Envoie-lui ce lien. Il pourra rejoindre gratuitement. Tu peux déjà commencer.": "أرسل إليه هذا الرابط. يمكنه الانضمام مجانًا. ويمكنك البدء من الآن.",
  "Envoyer": "إرسال",
  "Envoyer ma demande": "إرسال طلبي",
  "Envoyer sur WhatsApp": "إرسال عبر واتساب",
  "Étape {a} · {b}": "المرحلة {a} · {b}",
  "Étapes": "المراحل",
  "Étapes de l'abonnement": "مراحل الاشتراك",
  "ex : 46 12 34 56": "مثال: 46 12 34 56",
  "ex : Cardiologie": "مثال: أمراض القلب",
  "ex : FMPOS UNAM, UCAD, Université Hassan II…": "مثال: FMPOS UNAM، UCAD، جامعة الحسن الثاني…",
  "ex : Insuffisance cardiaque": "مثال: فشل القلب",
  "ex : le C3 n'est pas normal dans cette maladie, d'après mon cours.": "مثال: قيمة C3 ليست عادية في هذا المرض، حسب درسي.",
  "ex : Mariem, Cheikh, Awa…": "مثال: مريم، الشيخ، أوا…",
}
