/* Traductions arabes, partie 2. */
export const AR2: Record<string, string> = {
  "Facile": "سهلة",
  "Faire un QCM": "حلّ QCM",
  "Fais ton paiement": "قم بالدفع",
  "FCFA": "فرنك CFA",
  "Fermer": "إغلاق",
  "Fermer la liste": "إغلاق القائمة",
  "Fermer le menu": "إغلاق القائمة",
  "Fermer le message": "إغلاق الرسالة",
  "Feu de bois": "نار الحطب",
  "Feu qui crépite sous la pluie": "نار تطقطق تحت المطر",
  "Fiche": "الملخّص",
  "Fiche de révision": "ملخّص المراجعة",
  "Filière": "التخصص",
  "Flashcards": "بطاقات المراجعة",
  "Focus": "تركيز",
  "Forêt": "غابة",
  "français": "الفرنسية",
  "Free Money": "Free Money",
  "Génère des cas cliniques pour ce cours.": "أنشئ حالات سريرية لهذا الدرس.",
  "Génère la fiche de ce cours.": "أنشئ ملخّص هذا الدرس.",
  "Génère les flashcards de ce cours.": "أنشئ بطاقات المراجعة لهذا الدرس.",
  "Générer 5 QCM": "إنشاء 5 أسئلة QCM",
  "Générer la fiche": "إنشاء الملخّص",
  "Générer les cas cliniques": "إنشاء الحالات السريرية",
  "Générer les flashcards": "إنشاء بطاقات المراجعة",
  "Gérer →": "إدارة ←",
  "Gratuit": "مجاني",
  "Grave et enveloppant": "عميق ومحيط",
  "Grondements lointains": "رعد بعيد",
  "Heure": "الساعة",
  "Hier": "أمس",
  "Il lui reste des questions : son score peut encore changer.": "بقيت له أسئلة: قد تتغير نتيجته.",
  "Il y avait beaucoup de bruit autour de toi : relis le texte et corrige-le avant d'envoyer.": "كان هناك ضجيج كثير حولك: أعد قراءة النص وصحّحه قبل الإرسال.",
  "Image jointe {a}": "الصورة المرفقة {a}",
  "Impossible d'ajouter ce fichier. Vérifie qu'il s'agit d'un PDF, d'un fichier .txt ou de photos de ton cours, puis réessaie.": "تعذّرت إضافة هذا الملف. تأكد أنه PDF أو ملف .txt أو صور لدرسك، ثم حاول مجددًا.",
  "Impossible d'ajouter cette session. Réessaie dans un instant.": "تعذّرت إضافة هذه الجلسة. حاول بعد قليل.",
  "Impossible d'enregistrer tes modifications pour le moment. Réessaie dans un instant.": "تعذّر حفظ تعديلاتك حاليًا. حاول بعد قليل.",
  "Impossible d'enregistrer ton profil pour le moment. Réessaie dans un instant.": "تعذّر حفظ ملفك الشخصي حاليًا. حاول بعد قليل.",
  "Impossible d'envoyer pour le moment. Écris-nous sur WhatsApp si c'est urgent.": "تعذّر الإرسال حاليًا. راسلنا على واتساب إن كان الأمر عاجلًا.",
  "Impossible d'envoyer ta demande pour le moment. Vérifie ta connexion et réessaie.": "تعذّر إرسال طلبك حاليًا. تحقّق من اتصالك وحاول مجددًا.",
  "Impossible d'ouvrir la page de paiement pour le moment. Réessaie dans un instant.": "تعذّر فتح صفحة الدفع حاليًا. حاول بعد قليل.",
  "Impossible de charger ton planning pour le moment.": "تعذّر تحميل جدولك حاليًا.",
  "Inviter quelqu'un": "ادعُ شخصًا",
  "J'ai réfléchi, étape suivante": "فكّرت، المرحلة التالية",
  "Je n'ai pas compris ce qui a été dit. Rapproche-toi du micro, dans un endroit calme, et réessaie.": "لم أفهم ما قيل. اقترب من الميكروفون في مكان هادئ وحاول مجددًا.",
  "Je n'arrive pas à lire assez de texte. Prends la page bien à plat, dans une bonne lumière, sans reflet, puis réessaie.": "لا أستطيع قراءة نص كافٍ. صوّر الصفحة مسطّحة في إضاءة جيدة دون انعكاس، ثم حاول مجددًا.",
  "Je n'entends presque rien : le micro est peut-être coupé, mal choisi ou trop loin de toi.": "لا أسمع شيئًا تقريبًا: ربما الميكروفون مقطوع أو غير مناسب أو بعيد عنك.",
  "Je t'écoute… {a}": "أنا أستمع… {a}",
  "Joindre une image": "إرفاق صورة",
  "Jour sélectionné": "اليوم المحدد",
  "Jusqu'à 30 cartes question / réponse sur l'essentiel de ton cours, dans l'ordre des chapitres. Elles sont enregistrées : tu les génères une seule fois.":
    "حتى 30 بطاقة سؤال / جواب عن أهم ما في درسك، بترتيب الفصول. تُحفظ البطاقات: تنشئها مرة واحدة فقط.",
  "Jusqu'au {a}": "حتى {a}",
  "K7M4QX": "K7M4QX",
  "L'enregistrement est trop court. Appuie sur le micro, parle, puis rappuie pour terminer.": "التسجيل قصير جدًا. اضغط على الميكروفون، تكلّم، ثم اضغط مجددًا للإنهاء.",
  "L'historique des QCM n'est pas encore activé sur ce compte. Tes séries ne sont pas enregistrées pour le moment.": "سجل أسئلة QCM غير مفعّل بعد على هذا الحساب. سلاسلك غير محفوظة حاليًا.",
  "L'historique n'est pas encore activé : tes discussions ne sont pas enregistrées.": "السجل غير مفعّل بعد: محادثاتك غير محفوظة.",
  "La dictée vocale n'est pas encore activée.": "الإملاء الصوتي غير مفعّل بعد.",
  "La génération n'a pas abouti. Réessaie.": "لم تنجح عملية الإنشاء. حاول مجددًا.",
  "La musique n'est pas disponible pour le moment.": "الموسيقى غير متاحة حاليًا.",
  "La série « {a} » du {b} sera supprimée définitivement.": "ستُحذف السلسلة «{a}» بتاريخ {b} نهائيًا.",
  "La transcription a échoué. Réessaie ou écris ta question.": "فشل التفريغ الصوتي. حاول مجددًا أو اكتب سؤالك.",
  "Lance un Pomodoro : chaque bloc terminé s'affiche ici.": "ابدأ جولة بومودورو: تظهر هنا كل جولة منتهية.",
  "Lance une session": "ابدأ جلسة",
  "Lancer le son": "تشغيل الصوت",
  "Lancer un Pomodoro": "بدء بومودورو",
  "Lancer une session est réservé au plan Duo.": "بدء جلسة مخصّص لاشتراك Duo.",
  "Langue de la dictée : {a}. Changer.": "لغة الإملاء: {a}. اضغط للتغيير.",
  "Langue de la dictée (automatique, français ou arabe)": "لغة الإملاء (تلقائي، فرنسية أو عربية)",
  "Le code a 6 caractères (lettres et chiffres).": "الرمز مكوّن من 6 أحرف (حروف وأرقام).",
  "Le compteur repart demain.": "يبدأ العدّاد من جديد غدًا.",
  "Le même abonnement marche sur le site et dans l'application.": "الاشتراك نفسه يعمل على الموقع وفي التطبيق.",
  "Le micro est bloqué. Autorise-le dans ton navigateur pour dicter ta question.": "الميكروفون محظور. اسمح به في متصفحك لإملاء سؤالك.",
  "Le numéro avec lequel tu paies aide à retrouver ton paiement plus vite.": "الرقم الذي تدفع به يساعد على إيجاد دفعتك بسرعة.",
  "Le paiement en ligne arrive bientôt. En attendant, écris-nous sur WhatsApp : nous activons ton plan {a} avec toi.": "الدفع عبر الإنترنت قريبًا. في انتظاره راسلنا على واتساب: نفعّل معك اشتراك {a}.",
  "Le plan {a} en offre {b} par jour.": "اشتراك {a} يتيح {b} يوميًا.",
  "Le plus choisi": "الأكثر اختيارًا",
  "Lecture de la page {a} sur {b}…": "قراءة الصفحة {a} من {b}…",
  "Lecture du fichier…": "جارٍ قراءة الملف…",
  "Les moyens de paiement ne sont pas encore disponibles ici. Écris-nous sur WhatsApp pour t'abonner.": "وسائل الدفع غير متاحة هنا بعد. راسلنا على واتساب للاشتراك.",
  "Les points essentiels du cours, prêts à réviser, à télécharger en PDF.": "أهم نقاط الدرس جاهزة للمراجعة، وقابلة للتنزيل بصيغة PDF.",
  "Les QCM n'ont pas pu être générés. Réessaie.": "تعذّر إنشاء أسئلة QCM. حاول مجددًا.",
  "Les réponses de {a} s'affichent une fois que tu as validé la question.": "تظهر إجابات {a} بعد أن تجيب أنت عن السؤال.",
  "Lien copié": "تم نسخ الرابط",
  "Lieux": "أماكن",
  "Limite du jour": "حدّ اليوم",
  "Lire la playlist": "تشغيل قائمة الأغاني",
  "Lo-fi": "Lo-fi",
  "Lo-fi {n}": "Lo-fi {n}",
  "M'entraîner": "تدرّب",
  "MAD": "درهم",
  "maîtrisée": "متقنة",
  "Marquer comme à faire": "وضع علامة «لم تُنجز»",
  "Marquer comme faite": "وضع علامة «أُنجزت»",
  "Masque les bruits": "يحجب الضوضاء",
  "Matière": "المادة",
  "Matin en forêt": "صباح في الغابة",
  "Me tester": "اختبر نفسي",
  "Médecine": "الطب",
  "Mémoriser": "احفظ",
  "Mensuel": "شهري",
  "Mer calme": "بحر هادئ",
  "Merci, c'est envoyé.": "شكرًا، تم الإرسال.",
  "Mes cours": "دروسي",
  "Mettre le son en pause": "إيقاف الصوت مؤقتًا",
  "Mettre le son en pause pendant les pauses du minuteur": "إيقاف الصوت مؤقتًا أثناء استراحات المؤقت",
  "Mobile money": "الدفع عبر الهاتف",
  "Modifications enregistrées.": "تم حفظ التعديلات.",
  "Mois précédent": "الشهر السابق",
  "Mois suivant": "الشهر التالي",
  "Mon compte": "حسابي",
  "Mon dernier mélange": "آخر مزيج لي",
  "Morceau précédent": "المقطوعة السابقة",
  "Morceau suivant": "المقطوعة التالية",
  "Moyens de paiement": "وسائل الدفع",
  "MRU": "MRU",
  "Murmures et tasses": "همسات وفناجين",
  "Musique · playlists": "موسيقى · قوائم تشغيل",
  "Nappes calmes": "ألحان هادئة",
  "Nappes calmes {n}": "ألحان هادئة {n}",
  "Nature": "طبيعة",
  "Nature {n}": "طبيعة {n}",
  "Navigation principale": "التنقل الرئيسي",
  "Ne ferme pas cette page, ça prend quelques secondes.": "لا تغلق هذه الصفحة، يستغرق الأمر بضع ثوانٍ.",
  "Niveau du micro": "مستوى الميكروفون",
  "Note-toi honnêtement : la carte reviendra au bon moment": "قيّم نفسك بصدق: ستعود البطاقة في الوقت المناسب",
  "Nous attendons la confirmation.": "ننتظر التأكيد.",
  "Nous prévenir sur WhatsApp": "أبلغنا عبر واتساب",
  "Nous vérifions ton reçu. Ton plan {a} est activé sous 24 heures, sur le site et dans l'application.": "نتحقق من إيصالك. يُفعَّل اشتراك {a} خلال 24 ساعة، على الموقع وفي التطبيق.",
  "Nouveau titre": "عنوان جديد",
  "Nouvelle discussion": "محادثة جديدة",
  "Nouvelle série de QCM": "سلسلة QCM جديدة",
  "Nuit d'orage": "ليلة عاصفة",
  "Oiseaux": "طيور",
  "Oiseaux, vent, ruisseau": "طيور، رياح، جدول ماء",
  "Orage": "عاصفة",
  "Orange Money": "Orange Money",
  "Organiser": "التنظيم",
  "Outils": "الأدوات",
  "Ouverture de l'invitation…": "جارٍ فتح الدعوة…",
  "Ouverture du paiement…": "جارٍ فتح الدفع…",
  "Ouvre un cours, onglet QCM.": "افتح درسًا، ثم تبويب QCM.",
  "Ouvre-le pour poser tes questions à Dr. Ahmed, générer une fiche, te tester avec des QCM ou apprendre avec des flashcards.": "افتحه لتطرح أسئلتك على الدكتور أحمد، أو لتنشئ ملخّصًا، أو لتختبر نفسك بأسئلة QCM، أو لتحفظ ببطاقات المراجعة.",
  "Ouvrir": "فتح",
  "Ouvrir et réviser": "افتح وراجع",
  "Ouvrir la liste des discussions": "فتح قائمة المحادثات",
  "Ouvrir le menu": "فتح القائمة",
  "Paiement": "الدفع",
  "Paiement annulé.": "تم إلغاء الدفع.",
  "Paiement au Sénégal": "الدفع في السنغال",
  "Paiement reçu. Ton plan est activé.": "تم استلام الدفع. اشتراكك مفعّل.",
  "Parle plus fort ou rapproche-toi": "تكلّم بصوت أعلى أو اقترب",
  "Partenaire": "الشريك",
  "Pas de répétition": "بلا تكرار",
  "Pas encore de partenaire.": "لا يوجد شريك بعد.",
  "Pas encore répondu": "لم يُجب بعد",
  "pas encore validée": "لم تُجَب بعد",
  "Passe à Standard": "انتقل إلى Standard",
  "Passer à Standard": "الانتقال إلى Standard",
  "Pause": "استراحة",
  "Payer {a} {b}": "ادفع {a} {b}",
  "Payer {a} MRU": "ادفع ⁦{a} MRU⁩",
  "Pays": "البلد",
  "Personne n'a encore rejoint.": "لم ينضم أحد بعد.",
  "Pharmacie": "الصيدلة",
  "Phase": "المرحلة",
  "Photos de cours du {a}": "صور دروس بتاريخ {a}",
  "Plan {a}": "اشتراك {a}",
  "Planifie tes sessions de révision. Elles apparaissent sur le calendrier, avec le temps travaillé en Pomodoro.": "خطّط جلسات مراجعتك. تظهر في التقويم مع الوقت الذي عملت فيه بنظام بومودورو.",
  "Planifier": "تخطيط",
  "Planifier une session": "تخطيط جلسة",
  "Planning": "التخطيط",
  "Planning →": "التخطيط ←",
  "Playlist": "قائمة تشغيل",
  "Playlist de beats doux": "قائمة إيقاعات هادئة",
  "Pluie {n}": "مطر {n}",
  "Pluie douce": "مطر خفيف",
  "Pluie et tonnerre": "مطر ورعد",
  "Plus ancien": "الأقدم",
  "Plus de questions et de QCM": "مزيد من الأسئلة وأسئلة QCM",
  "Plus tard": "لاحقًا",
  "Pomodoro": "بومودورو",
  "Pose ta question sur ce cours.": "اطرح سؤالك عن هذا الدرس.",
  "Pose ta question…": "اطرح سؤالك…",
  "Pose une question libre, ou choisis un de tes cours pour une réponse tirée de ton document.": "اطرح سؤالًا حرًّا، أو اختر أحد دروسك للحصول على جواب مأخوذ من مستندك.",
  "Poser une question": "اطرح سؤالًا",
  "Poser une question à Dr. Ahmed": "اطرح سؤالًا على الدكتور أحمد",
  "Premiers pas": "الخطوات الأولى",
  "Prends une capture d'écran du reçu": "التقط لقطة شاشة للإيصال",
  "Prénom": "الاسم الأول",
  "Profil": "الملف الشخصي",
  "QCM": "QCM",
  "Qu'est-ce qui est faux ?": "ما الخطأ؟",
  "Quatre infos pour adapter Dr. Ahmed à ton niveau. Ça prend 30 secondes.": "أربع معلومات لتكييف الدكتور أحمد مع مستواك. تستغرق 30 ثانية.",
  "Que veux-tu faire avec ce cours ?": "ماذا تريد أن تفعل بهذا الدرس؟",
  "Question": "السؤال",
  "Question {a}": "السؤال {a}",
  "Question {a} sur {b}": "السؤال {a} من {b}",
  "Questions": "الأسئلة",
  "Questions aujourd'hui": "أسئلة اليوم",
  "Questions restantes aujourd'hui": "الأسئلة المتبقية اليوم",
}
